apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data1
spec:
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
